# Generated by Django 5.0.6 on 2024-07-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='etudiant_compte',
        ),
    ]
