# Generated by Django 5.0.6 on 2024-07-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_etudiant_compte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='etudiant_compte',
        ),
    ]
